#!/usr/bin/env bash
# Discover the hermes-machine SSH port and write the Ansible inventory.
# This file is gitignored — it's generated fresh before each Ansible run.
set -euo pipefail

MACHINE_NAME="hermes-machine"
OUT="ansible/inventory/hermes-machine.yml"

# Extract the SSH port from podman machine's ssh-config output
SSH_PORT=$(podman machine ssh-config "$MACHINE_NAME" 2>/dev/null \
  | awk '/Port / {print $2}')

if [[ -z "$SSH_PORT" ]]; then
  echo "ERROR: Could not determine SSH port for $MACHINE_NAME." >&2
  echo "       Is the machine running? Run: podman machine start $MACHINE_NAME" >&2
  exit 1
fi

# Discover the VM bridge interface by finding which host interface routes to the VM's IP.
# podman machine inspect doesn't expose the bridge name directly (Docker schema != Podman schema).
VM_IP=$(podman machine ssh-config "$MACHINE_NAME" 2>/dev/null | awk '/HostName/ {print $2}')
VM_BRIDGE_IFACE=$(route get "$VM_IP" 2>/dev/null | awk '/interface:/ {print $2}')
VM_BRIDGE_IFACE="${VM_BRIDGE_IFACE:-bridge100}"   # fallback: bridge100 is the Podman default on macOS

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# Generated by scripts/gen-inventory.sh — do not edit by hand
all:
  hosts:
    hermes-machine:
      ansible_host: 127.0.0.1
      ansible_port: ${SSH_PORT}
      ansible_user: core
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      vm_bridge_iface: "${VM_BRIDGE_IFACE}"
EOF

echo "Wrote $OUT (port=$SSH_PORT, bridge=$VM_BRIDGE_IFACE)"
