"""Interfaces (ISP / DIP) — cogs depend on these, not on concrete classes."""
from typing import Protocol, runtime_checkable


@runtime_checkable
class IHistory(Protocol):
    def get(self, channel_id: int) -> list[dict]: ...
    def add(self, channel_id: int, role: str, content: str) -> None: ...
    def clear(self, channel_id: int) -> None: ...


@runtime_checkable
class IMessageTracker(Protocol):
    def track(self, msg: object) -> None: ...
    def last(self, channel_id: int) -> object | None: ...
    def pop_recent(self, channel_id: int, n: int) -> list: ...


@runtime_checkable
class IModelState(Protocol):
    @property
    def current(self) -> str: ...
    @property
    def allowed(self) -> list[str]: ...
    @property
    def aliases(self) -> dict[str, str]: ...
    def resolve(self, name: str) -> str | None: ...
    def switch(self, name: str) -> str: ...
